/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalholp2.Telas;

import com.mycompany.trabalholp2.Classes.Produto;
import DAO.FornecedorDAO;
import DAO.InterfaceProdDAO;
import DAO.ProdutoDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menu.menuOpcoes;

/**
 *
 * @author Kayky
 */
public class TelaDeExcluirProduto extends javax.swing.JFrame {
    
    private boolean mostrandoProdutos;
    /**
     * Creates new form TelaDeExcluir
     */
    public TelaDeExcluirProduto() {
        initComponents();
        this.mostrandoProdutos = false;
        
    }
    public void listarProdutos() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTabela.getModel();
        InterfaceProdDAO dao = new ProdutoDAO();
        List<Produto> produtos = new ArrayList<Produto>();
        
        try {
            
            produtos = dao.exibirDadosProduto();

            modelo.setRowCount(0);

            for (Produto p : produtos) {
                
                modelo.addRow(new Object[]{
                    
                    p.getId(),
                    p.getNome_prod(),
                    p.getCategoria(),
                    p.getQtde(),
                    p.getFornecedor()
                        
                });
            }

            
            jRotuloSituacao.setText("Mostrando produtos.");
            this.mostrandoProdutos = true;
            
        } catch (Exception ex) {
            
            jRotuloResultado.setText("Erro ao listar produtos\n" + ex.getMessage());
            
        }
        finally {
            
            produtos = null;
            dao = null;
            
        }
    }
   /* 

    */
    private void excluirSelecionado() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTabela.getModel();
        int linha = jTabela.getSelectedRow();       
        Integer id = (int) modelo.getValueAt(linha, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o item selecionado?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) return;
        
        if (linha == -1) {
            
            JOptionPane.showMessageDialog(this, "Selecione uma linha para excluir.");
            return;
            
            }

        try {
                        
            if (mostrandoProdutos) {
                
                InterfaceProdDAO dao = new ProdutoDAO();
                Produto produto = new Produto();
                produto.setId(id);
                dao.excluirProduto(produto);
                listarProdutos();
                JOptionPane.showMessageDialog(this, "Produto excluido com sucesso");
                
            }            
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(this, "Falha ao excluir o produto");
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBotaoMostrarProd = new javax.swing.JButton();
        jRotuloSituacao = new javax.swing.JLabel();
        jRotuloResultado = new javax.swing.JLabel();
        jBotaoExcluir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jBotaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tela de exclusão de produto");

        jBotaoMostrarProd.setText("MOSTRAR PRODUTOS");
        jBotaoMostrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoMostrarProdActionPerformed(evt);
            }
        });

        jBotaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/trabalholp2/imagens/waste-reduction_18500412.png"))); // NOI18N
        jBotaoExcluir.setText("EXCLUIR SELECIONADO");
        jBotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoExcluirActionPerformed(evt);
            }
        });

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Quantidade", "Categoria", "Fornecedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTabela);

        jBotaoVoltar.setText("VOLTAR");
        jBotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBotaoVoltar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBotaoExcluir)
                                    .addComponent(jRotuloResultado))
                                .addGap(0, 165, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jBotaoMostrarProd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRotuloSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBotaoVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotaoMostrarProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBotaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRotuloSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRotuloResultado))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoExcluirActionPerformed
        // TODO add your handling code here:
        this.excluirSelecionado();
    }//GEN-LAST:event_jBotaoExcluirActionPerformed

    private void jBotaoMostrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoMostrarProdActionPerformed
        // TODO add your handling code here:
        this.listarProdutos();
    }//GEN-LAST:event_jBotaoMostrarProdActionPerformed

    private void jBotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new menuOpcoes().setVisible(true);
    }//GEN-LAST:event_jBotaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeExcluirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeExcluirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeExcluirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeExcluirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeExcluirProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotaoExcluir;
    private javax.swing.JButton jBotaoMostrarProd;
    private javax.swing.JButton jBotaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jRotuloResultado;
    private javax.swing.JLabel jRotuloSituacao;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabela;
    // End of variables declaration//GEN-END:variables
}
