package com.mycompany.trabalholp2;
/**
 *
 * @author Breno de Souza
 */
public class TelaCadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroFornecedor
     */
    public TelaCadastroFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRotuloNomeForn = new javax.swing.JLabel();
        jTxtNomeForn = new javax.swing.JTextField();
        jRotuloCnpjForn = new javax.swing.JLabel();
        jTxtCnpjForn = new javax.swing.JTextField();
        jRotuloTelForn = new javax.swing.JLabel();
        jTxtTelForn = new javax.swing.JTextField();
        jRotuloEmailForn = new javax.swing.JLabel();
        jTxtEmailForn = new javax.swing.JTextField();
        jRotuloEndForn = new javax.swing.JLabel();
        jTxtEndForn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBotaoEnviar = new javax.swing.JButton();
        jBotaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRotuloNomeForn.setText("Nome");

        jTxtNomeForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeFornActionPerformed(evt);
            }
        });

        jRotuloCnpjForn.setText("CNPJ");

        jTxtCnpjForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCnpjFornActionPerformed(evt);
            }
        });

        jRotuloTelForn.setText("Tel");

        jRotuloEmailForn.setText("Email");

        jRotuloEndForn.setText("End");

        jLabel6.setText("Tela de cadastro do fornecedor");

        jBotaoEnviar.setText("Enviar");
        jBotaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoEnviarActionPerformed(evt);
            }
        });

        jBotaoVoltar.setText("Voltar");
        jBotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRotuloEndForn)
                            .addComponent(jRotuloEmailForn)
                            .addComponent(jRotuloTelForn)
                            .addComponent(jRotuloCnpjForn)
                            .addComponent(jRotuloNomeForn))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtNomeForn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jTxtCnpjForn)
                            .addComponent(jTxtTelForn)
                            .addComponent(jTxtEmailForn)
                            .addComponent(jTxtEndForn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBotaoVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBotaoEnviar)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRotuloNomeForn)
                    .addComponent(jTxtNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRotuloCnpjForn)
                    .addComponent(jTxtCnpjForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRotuloTelForn)
                    .addComponent(jTxtTelForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRotuloEmailForn)
                    .addComponent(jTxtEmailForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRotuloEndForn)
                    .addComponent(jTxtEndForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoEnviar)
                    .addComponent(jBotaoVoltar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCnpjFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCnpjFornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCnpjFornActionPerformed

    private void jBotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotaoVoltarActionPerformed

    private void jTxtNomeFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeFornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeFornActionPerformed

    private void jBotaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoEnviarActionPerformed
        // TODO add your handling code here:
        Fornecedor fornecedor;
        fornecedor = new Fornecedor (jTxtNomeForn.getText(), jTxtCnpjForn.getText()
                , jTxtTelForn.getText(), jTxtEmailForn.getText(), jTxtEndForn.getText());
        
        //LogCadastroFornecedor logForn = new LogCadastroFornecedor();        
        //logForn.setVisible(true); 
        
    }//GEN-LAST:event_jBotaoEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotaoEnviar;
    private javax.swing.JButton jBotaoVoltar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jRotuloCnpjForn;
    private javax.swing.JLabel jRotuloEmailForn;
    private javax.swing.JLabel jRotuloEndForn;
    private javax.swing.JLabel jRotuloNomeForn;
    private javax.swing.JLabel jRotuloTelForn;
    private javax.swing.JTextField jTxtCnpjForn;
    private javax.swing.JTextField jTxtEmailForn;
    private javax.swing.JTextField jTxtEndForn;
    private javax.swing.JTextField jTxtNomeForn;
    private javax.swing.JTextField jTxtTelForn;
    // End of variables declaration//GEN-END:variables
}
