/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalholp2.Telas;

import com.mycompany.trabalholp2.Classes.Fornecedor;
import DAO.FornecedorDAO;
import DAO.InterfaceFornDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import menu.MDI;

/**
 *
 * @author Kayky
 */

public class TelaDeExcluirFornecedor extends JInternalFrame {
    private boolean mostrandoFornecedores;
    /**
     * Creates new form TelaDeExcluirFornecedor
     */
    
    public TelaDeExcluirFornecedor() {
        super("Tela de exclusao do fornecedor", true, true, true, true);
        initComponents();
        mostrandoFornecedores = false;
    }
    
    public void listarFornecedores() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTabela.getModel();
        InterfaceFornDAO dao = new FornecedorDAO();
        List<Fornecedor> fornecedores = new ArrayList<Fornecedor>();
        
        try {
            
            fornecedores = dao.exibirDadosFornecedor();            
            modelo.setRowCount(0);
            
            for (Fornecedor f : fornecedores) {
                
                modelo.addRow(new Object[]{
                    
                    f.getId(),
                    f.getNome(),
                    f.getCNPJ(),
                    f.getTelefone(),
                    f.getEmail()
                        
                });
            }
           
            jRotuloSituacao.setText("Mostrando fornecedores.");
            this.mostrandoFornecedores = true;
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao listar fornecedores: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
      private void excluirSelecionado() {
    try {
        DefaultTableModel modelo = (DefaultTableModel) jTabela.getModel();
        
        int linha = jTabela.getSelectedRow();       
        int coluna = jTabela.getSelectedColumn();
        
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para excluir.");
            return;
        }
        
        if (coluna != 0){
            JOptionPane.showMessageDialog(this, "Selecione o ID de um fornecedor para excluir.");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o item selecionado?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        Integer id = (int) modelo.getValueAt(linha, 0);

        if (mostrandoFornecedores) {
            InterfaceFornDAO dao = new FornecedorDAO();
            Fornecedor fornecedor = new Fornecedor();
            fornecedor.setId(id);
            dao.excluirFornecedor(fornecedor);
            listarFornecedores();
            JOptionPane.showMessageDialog(this, "Fornecedor excluído com sucesso");
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Falha ao excluir o Fornecedor");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jAviso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBotaoSair = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jBotaoMostrarProd = new javax.swing.JButton();
        jRotuloResultado = new javax.swing.JLabel();
        jRotuloSituacao = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();

        jAviso.setText("Selecione um ID para excluir");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jAviso)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jAviso)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tela de exclusão de fornecedor");

        jBotaoSair.setText("SAIR");
        jBotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoSairActionPerformed(evt);
            }
        });

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CNPJ", "Telefone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTabela);

        jBotaoMostrarProd.setText("MOSTRAR FORNECEDORES");
        jBotaoMostrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoMostrarProdActionPerformed(evt);
            }
        });

        jRotuloResultado.setText(",");

        jRotuloSituacao.setPreferredSize(new java.awt.Dimension(3, 16));

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRotuloSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRotuloResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBotaoSair))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jBotaoMostrarProd)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jBotaoSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotaoMostrarProd)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRotuloResultado)
                    .addComponent(jRotuloSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoSairActionPerformed
// TODO add your handling code here:
        
        this.dispose();

        
    }//GEN-LAST:event_jBotaoSairActionPerformed

    private void jBotaoMostrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoMostrarProdActionPerformed
        // TODO add your handling code here:
        this.listarFornecedores();
    }//GEN-LAST:event_jBotaoMostrarProdActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
           this.excluirSelecionado();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeExcluirFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeExcluirFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeExcluirFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeExcluirFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeExcluirFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAviso;
    private javax.swing.JButton jBotaoMostrarProd;
    private javax.swing.JButton jBotaoSair;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jRotuloResultado;
    private javax.swing.JLabel jRotuloSituacao;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabela;
    // End of variables declaration//GEN-END:variables
}
