/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import com.mycompany.trabalholp2.Telas.TelaCadastroFornecedor;
import com.mycompany.trabalholp2.Telas.TelaCadastroProduto;
import com.mycompany.trabalholp2.Telas.TelaEditarFornecedor;
import com.mycompany.trabalholp2.Telas.telaEditarProduto;

/**
 *
 * @author Cristiano
 */
public class menuOpcoes extends javax.swing.JFrame {

    /**
     * Creates new form menuOpcoes
     */
    public menuOpcoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBotaoCadastrarForn = new javax.swing.JButton();
        jBotaoCadastrarProd = new javax.swing.JButton();
        jBotaoEditarForn = new javax.swing.JButton();
        jBotaoEditarProd = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBotaoCadastrarForn.setText("Cadastrar fornecedor");
        jBotaoCadastrarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoCadastrarFornActionPerformed(evt);
            }
        });

        jBotaoCadastrarProd.setText("Cadastrar produto");
        jBotaoCadastrarProd.setToolTipText("");
        jBotaoCadastrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoCadastrarProdActionPerformed(evt);
            }
        });

        jBotaoEditarForn.setText("Editar Dados Fornecedor");
        jBotaoEditarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoEditarFornActionPerformed(evt);
            }
        });

        jBotaoEditarProd.setText("Editar Dados Produto");
        jBotaoEditarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoEditarProdActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        jButton7.setText("Exibir fornecedores cadastrados");

        jButton8.setText("exibir produtos cadastrados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7)
                    .addComponent(jButton5)
                    .addComponent(jBotaoEditarForn)
                    .addComponent(jBotaoCadastrarForn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBotaoCadastrarProd)
                    .addComponent(jBotaoEditarProd)
                    .addComponent(jButton6)
                    .addComponent(jButton8))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoCadastrarForn)
                    .addComponent(jBotaoCadastrarProd))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoEditarForn)
                    .addComponent(jBotaoEditarProd))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotaoCadastrarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoCadastrarFornActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaCadastroFornecedor().setVisible(true);        
    }//GEN-LAST:event_jBotaoCadastrarFornActionPerformed

    private void jBotaoCadastrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoCadastrarProdActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaCadastroProduto().setVisible(true);
        
    }//GEN-LAST:event_jBotaoCadastrarProdActionPerformed

    private void jBotaoEditarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoEditarFornActionPerformed
    this.dispose();
    new TelaEditarFornecedor().setVisible(true);
    }//GEN-LAST:event_jBotaoEditarFornActionPerformed

    private void jBotaoEditarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoEditarProdActionPerformed
    this.dispose();
    new telaEditarProduto().setVisible(true);
    }//GEN-LAST:event_jBotaoEditarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuOpcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotaoCadastrarForn;
    private javax.swing.JButton jBotaoCadastrarProd;
    private javax.swing.JButton jBotaoEditarForn;
    private javax.swing.JButton jBotaoEditarProd;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    // End of variables declaration//GEN-END:variables
}
